services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - wp4-db:/backend/instance
      - wp4-images:/backend/static/user_images
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=0

volumes:
  wp4-db:
  wp4-images: