version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/instance:/app/instance
    environment:
      - FLASK_ENV=development
